### ISSUE TITLE
when remove debounced hit error use nested lookups.

### ISSUE THREAD

**Issue by fangjj** [kschingiz/publish-lookups#2]
i'm confused about this.
lookup.js
```
class PublishLookup {
  constructor(collection, selector, options, lookups) {
    ....
    // this.republishLookups = debounced(this.republishLookups.bind(this));
    // this.republishChildLookups = debounced(
    //   this.republishChildLookups.bind(this)
    // );
```
publish.js
```
return Posts.lookup({_id: "GQHhqas6W33Cpiqyc"}, {}, [
    {
      collection: Comments,
      localField: "_id",
      foreignField: "postId",
      selector: {},
      options: { fields: { text: 1, } },
      lookups: [
        {
          collection: Authors,
          localField: "author",
          foreignField: "username",
          selector: {},
        }
      ]
    },
    {
      collection: Authors,
      localField: "author",
      foreignField: "username",
      selector: {},
      options: {}
    }
  ]);
```
error: ```
 Exception in added observe/observeChanges callback: Error: Can't call observeChanges from an observe callback on the same query
I20190722-08:53:30.531(8)?     at ObserveMultiplexer.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:40:13)
I20190722-08:53:30.531(8)?     at MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1346:15)
I20190722-08:53:30.532(8)?     at Cursor.observeChanges (packages/mongo/mongo_driver.js:947:22)
I20190722-08:53:30.532(8)?     at PublishLookup.publishLookups (packages/kschingiz:publish-lookups/lookup.js:151:29)
I20190722-08:53:30.532(8)?     at childLookups.forEach.publishLookup (packages/kschingiz:publish-lookups/lookup.js:40:21)
I20190722-08:53:30.532(8)?     at Array.forEach (<anonymous>)
I20190722-08:53:30.532(8)?     at PublishLookup.republishChildLookups (packages/kschingiz:publish-lookups/lookup.js:39:23)
I20190722-08:53:30.532(8)?     at added (packages/kschingiz:publish-lookups/lookup.js:113:20)
I20190722-08:53:30.533(8)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20190722-08:53:30.533(8)?     at packages/meteor.js:1299:14
I20190722-08:53:30.533(8)?     at packages/mongo/observe_multiplex.js:182:30
I20190722-08:53:30.533(8)?     at Array.forEach (<anonymous>)
I20190722-08:53:30.533(8)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20190722-08:53:30.533(8)?     at Object.task (packages/mongo/observe_multiplex.js:176:9)
I20190722-08:53:30.533(8)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
I20190722-08:53:30.534(8)?     at packages/meteor.js:894:12
```

**Comment by fangjj** [comment]
@kschingiz, hi, do you know why?

**Comment by kschingiz** [comment]
@fangjj Hi, the nested lookups feature is not yet developed and may break anytime. Currently it is breaking in you code because it tries to publish the document twice:
1. First published Author from Posts-Author lookup
2. Publishes the same Author from Comments-Author lookup

I am experiencing lack of free time and don't know yet when the feature will be ready, sorry.
